// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"database/sql"
)

type Patient struct {
	ID        int32        `json:"id"`
	FirstName string       `json:"first_name"`
	LastName  string       `json:"last_name"`
	Address   string       `json:"address"`
	Phone     string       `json:"phone"`
	Email     string       `json:"email"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Physician struct {
	ID        int32        `json:"id"`
	FirstName string       `json:"first_name"`
	LastName  string       `json:"last_name"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type Visit struct {
	ID          int32        `json:"id"`
	PatientID   int32        `json:"patient_id"`
	PhysicianID int32        `json:"physician_id"`
	VisitedAt   sql.NullTime `json:"visited_at"`
	Location    string       `json:"location"`
	Reason      string       `json:"reason"`
}
